# https://docs.docker.com/compose/compose-file/compose-file-v3/#reference-and-guidelines
# https://github.com/compose-spec/compose-spec/blob/master/spec.md
version: "3.8"
services:
  mongo1:
    hostname: mongo1
    container_name: localmongo1
    image: mongo:4.4.4-bionic
    expose:
      - 27017
    ports:
      - 27011:27017
    volumes:
      - mongo1:/data/db
    restart: always
    # https://docs.mongodb.com/manual/reference/program/mongod/
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
  mongo2:
    hostname: mongo2
    container_name: localmongo2
    image: mongo:4.4.4-bionic
    expose:
      - 27017
    ports:
      - 27012:27017
    volumes:
      - mongo2:/data/db
    restart: always
    # https://docs.mongodb.com/manual/reference/program/mongod/
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
  mongo3:
    hostname: mongo3
    container_name: localmongo3
    image: mongo:4.4.4-bionic
    expose:
      - 27017
    ports:
      - 27013:27017
    volumes:
      - mongo3:/data/db
    restart: always
    # https://docs.mongodb.com/manual/reference/program/mongod/
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
  vault:
    container_name: "vault"
    build:
      context: ./vault
      dockerfile: Dockerfile
    ports:
      - 8200:8200
      - 8201:8201
    volumes:
      - ./vault/config:/vault/config
      - ./vault/policies:/vault/policies
      - /c/Users/cap10bill/infra/vault/data:/vault/data
      - /c/Users/cap10bill/infra/vault/logs:/vault/logsF
    environment:
      - VAULT_API_ADDR=http://127.0.0.1:8200
    command: server -config=/vault/config/vault-config.json
    cap_add:
      - IPC_LOCK
    depends_on:
      - consul
  consul:
    container_name: "consul"
    build:
      context: ./consul
      dockerfile: Dockerfile
    ports:
      - 8300:8300
      - 8400:8400
      - 8500:8500
      - 8600:8600
    command: agent -server -bind 0.0.0.0 -client 0.0.0.0 -bootstrap-expect 1 -config-file=/consul/config/config.json
    volumes:
      - ./consul/config/consul-config.json:/consul/config/config.json
      - consul:/consul/data
  consul-worker:
    container_name: "consul_worker"
    build:
      context: ./consul
      dockerfile: Dockerfile
    command: agent -server -join consul -config-file=/consul/config/config.json
    volumes:
      - ./consul/config/consul-config.json:/consul/config/config.json
    depends_on:
      - consul
  management1:
    container_name: mysql-mgmt
    image: mysql/mysql-cluster
    volumes:
      - ./cluster-mysql/config/my.cnf:/etc/my.cnf
      - ./cluster-mysql/config/mysql-cluster.cnf:/etc/mysql-cluster.cnf
    command: "ndb_mgmd --ndb-nodeid=1"
    #command: ndb_mgmd
    networks:
      mysqlcluster:
        #        ipv4_address: 192.168.0.2
        ipv4_address: 172.28.0.2
  ndb1:
    container_name: "ndb1"
    image: mysql/mysql-cluster
    ports:
      - 1187:1186
    volumes:
      - ./cluster-mysql/config/my.cnf:/etc/my.cnf
      - ./cluster-mysql/config/mysql-cluster.cnf:/etc/mysql-cluster.cnf
    command: bash -c 'sleep 40; exec ndbd'
    #command: ndbd
    depends_on:
      - "management1"
    networks:
      mysqlcluster:
        #        ipv4_address: 192.168.0.3
        ipv4_address: 172.28.0.3
  ndb2:
    container_name: "ndb2"
    image: mysql/mysql-cluster
    ports:
      - 1188:1186
    volumes:
      - ./cluster-mysql/config/my.cnf:/etc/my.cnf
      - ./cluster-mysql/config/mysql-cluster.cnf:/etc/mysql-cluster.cnf
    command: bash -c 'sleep 40; exec ndbd'
    #command: ndbd
    depends_on:
      - "management1"
    networks:
      mysqlcluster:
        #        ipv4_address: 192.168.0.4
        ipv4_address: 172.28.0.4
  mysql1:
    container_name: "mysql1"
    image: mysql/mysql-cluster
    ports:
      - "3306:3306"
    volumes:
      - ./cluster-mysql/config/my.cnf:/etc/my.cnf
      - ./cluster-mysql/config/mysql-cluster.cnf:/etc/mysql-cluster.cnf
    #    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: bdteste
      MYSQL_USER: teste
      MYSQL_PASSWORD: teste
      MYSQL_ROOT_HOST: '%'
    command: bash -c 'sleep 60; exec mysqld'
    #command: mysqld
    depends_on:
      - "management1"
      - "ndb1"
      - "ndb2"
    networks:
      mysqlcluster:
        #        ipv4_address: 192.168.0.10
        ipv4_address: 172.28.0.10
  adminer:
    container_name: "adminer"
    image: adminer
    restart: always
    ports:
      - 8081:8080
    links:
      - mysql1:db
    networks:
      mysqlcluster:
volumes:
  mongo1:
  mongo2:
  mongo3:
  consul:

networks:
  mysqlcluster:
    #  driver: overlay
    driver: bridge
    ipam:
      config:
        #    - subnet: 192.168.0.0/16
        - subnet: 172.28.0.0/16
          gateway: 172.28.5.254
##    - ip-range: 172.28.5.0/24

#  docker run -it -v "$PWD/mysql.conf/my.cnf:/etc/my.cnf" -v "$PWD/mysql.conf/mysql-cluster.cnf:/etc/mysql-cluster.cnf" --net=mysqlcluster_mysqlcluster mysql/mysql-cluster ndb_mgm